spring:
  datasource:
    url: jdbc:mysql://localhost:3306/csc?characterEncoding=UTF8&socketTimeout=60000&&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      connection-timeout: 30000
      max-lifetime: 1800000

  jackson:
    joda-date-time-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis:
  typeAliasesPackage : com.example.dataplatform.model
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
